import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import scanAll from "../lib/client/ddb/scan-all";
import Card from "@/component/Card";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const _items: any = await scanAll();
  const items: string = JSON.stringify(_items);
  console.debug(`items=${items}`);
  // console.debug(`items[0]=${items[0]}`)
  // console.debug(`items[1]=${items[1]}`)
  // console.debug(`items[2]=${items[2]}`)
  // console.debug(`items[3]=${items[3]}`)
  return { props: { items } };
}

export default function Home({ items }: { items: string }) {
  return (
    <>
      <Head>
        <title>washify-next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Card item={items}></Card>
      </main>
    </>
  );
}
